const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

// ─── GET INSURER DASHBOARD ────────────────────────────────────────────────────
exports.getDashboard = async (req, res) => {
    try {
        const { id: insurerId } = req.insurer;

        const today = new Date();
        today.setHours(0, 0, 0, 0);
        const thisMonth = new Date(today.getFullYear(), today.getMonth(), 1);

        const [
            totalDrivers,
            activeDrivers,
            expiringDrivers,
            totalWrits,
            newWritsToday,
            newWritsMonth,
            unpaidInvoices
        ] = await Promise.all([
            prisma.driver.count({ where: { insurerId } }),
            prisma.driver.count({ where: { insurerId, status: 'ACTIVE' } }),
            // Policies expiring in next 30 days
            prisma.driver.count({
                where: {
                    insurerId,
                    status: 'ACTIVE',
                    policyExpiry: {
                        gte: today,
                        lte: new Date(today.getTime() + 30 * 24 * 60 * 60 * 1000)
                    }
                }
            }),
            prisma.accidentLog.count({
                where: { driver: { insurerId } }
            }),
            prisma.accidentLog.count({
                where: {
                    driver: { insurerId },
                    createdAt: { gte: today }
                }
            }),
            prisma.accidentLog.count({
                where: {
                    driver: { insurerId },
                    createdAt: { gte: thisMonth }
                }
            }),
            prisma.invoice.count({
                where: { insurerId, isPaid: false }
            })
        ]);

        return res.status(200).json({
            drivers: {
                total: totalDrivers,
                active: activeDrivers,
                expiringIn30Days: expiringDrivers
            },
            writs: {
                total: totalWrits,
                newToday: newWritsToday,
                newMonth: newWritsMonth
            },
            invoices: { unpaid: unpaidInvoices }
        });

    } catch (error) {
        console.error('AWAS V2 Insurer Dashboard Fault:', error);
        return res.status(500).json({ error: 'Ralat pelayan.' });
    }
};

// ─── GET MY POLICYHOLDERS ─────────────────────────────────────────────────────
exports.getMyDrivers = async (req, res) => {
    try {
        const { id: insurerId } = req.insurer;
        const { status, search } = req.query;

        const where = { insurerId };
        if (status) where.status = status;
        if (search) {
            where.OR = [
                { vehiclePlate: { contains: search.toUpperCase() } },
                { policyNumber: { contains: search.toUpperCase() } },
                { email: { contains: search.toLowerCase() } }
            ];
        }

        const drivers = await prisma.driver.findMany({
            where,
            orderBy: { createdAt: 'desc' },
            select: {
                id: true,
                vehiclePlate: true,
                vehicleMakeModel: true,
                vehicleType: true,
                phone: true,
                email: true,
                policyNumber: true,
                policyExpiry: true,
                status: true,
                createdAt: true,
                _count: { select: { accidentLogs: true } }
            }
        });

        return res.status(200).json({ count: drivers.length, drivers });

    } catch (error) {
        console.error('AWAS V2 getMyDrivers Fault:', error);
        return res.status(500).json({ error: 'Ralat pelayan.' });
    }
};

// ─── GET MY WRITS ─────────────────────────────────────────────────────────────
// Insurer views ALL writs generated by their policyholders
// This is the silent fraud detection mechanism
exports.getMyWrits = async (req, res) => {
    try {
        const { id: insurerId } = req.insurer;
        const { vehiclePlate, dateFrom, dateTo } = req.query;

        const where = {
            driver: { insurerId }
        };

        if (vehiclePlate) {
            where.vehiclePlate = vehiclePlate.toUpperCase();
        }

        if (dateFrom || dateTo) {
            where.createdAt = {};
            if (dateFrom) where.createdAt.gte = new Date(dateFrom);
            if (dateTo) where.createdAt.lte = new Date(dateTo);
        }

        const writs = await prisma.accidentLog.findMany({
            where,
            orderBy: { createdAt: 'desc' },
            include: {
                driver: {
                    select: {
                        vehiclePlate: true,
                        vehicleMakeModel: true,
                        vehicleType: true,
                        policyNumber: true,
                        phone: true,
                        email: true
                    }
                }
            }
        });

        return res.status(200).json({ count: writs.length, writs });

    } catch (error) {
        console.error('AWAS V2 getMyWrits Fault:', error);
        return res.status(500).json({ error: 'Ralat pelayan.' });
    }
};

// ─── GET SINGLE WRIT DETAIL ───────────────────────────────────────────────────
// Insurer views full writ detail — video, images, hashes
exports.getWritDetail = async (req, res) => {
    try {
        const { id: insurerId } = req.insurer;
        const { writNumber } = req.params;

        const log = await prisma.accidentLog.findUnique({
            where: { writNumber },
            include: {
                driver: {
                    select: {
                        insurerId: true,
                        vehiclePlate: true,
                        vehicleMakeModel: true,
                        vehicleType: true,
                        policyNumber: true,
                        policyExpiry: true,
                        phone: true,
                        email: true
                    }
                }
            }
        });

        if (!log) {
            return res.status(404).json({ error: 'Writ tidak dijumpai.' });
        }

        // Ensure insurer can only view their own policyholders' writs
        if (log.driver.insurerId !== insurerId) {
            return res.status(403).json({ error: 'Akses ditolak.' });
        }

        return res.status(200).json(log);

    } catch (error) {
        console.error('AWAS V2 getWritDetail Fault:', error);
        return res.status(500).json({ error: 'Ralat pelayan.' });
    }
};

// ─── GET MY INVOICES ──────────────────────────────────────────────────────────
exports.getMyInvoices = async (req, res) => {
    try {
        const { id: insurerId } = req.insurer;

        const invoices = await prisma.invoice.findMany({
            where: { insurerId },
            orderBy: { createdAt: 'desc' }
        });

        return res.status(200).json({ count: invoices.length, invoices });

    } catch (error) {
        console.error('AWAS V2 getMyInvoices Fault:', error);
        return res.status(500).json({ error: 'Ralat pelayan.' });
    }
};